apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  type: NodePort  # Exposes the service on each Node’s IP at a static port
  selector:
    app: myapp     # Must match the label in the deployment
  ports:
    - protocol: TCP
      port: 80           # Port exposed
